[package]
name = "live-journal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10"
chrono-tz = "0.4"
chrono = "0.4"